{% set name = "waybackpy" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/waybackpy-{{ version }}.tar.gz
  sha256: a4a2b3b7fbb9850d90b027f8d1a9d2a94483a962d36ba340194d62558f684b2c

build:
  entry_points:
    - waybackpy = waybackpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - python >=3.7
    - requests

test:
  imports:
    - waybackpy
  commands:
    - pip check
    - waybackpy --help
  requires:
    - pip

about:
  home: https://akamhy.github.io/waybackpy/
  summary: Python package that interfaces with the Internet Archive's Wayback Machine APIs. Archive pages and retrieve archived pages easily.
  dev_url: https://github.com/akamhy/waybackpy
  license: MIT
  license_file: LICENSE
  description: |
    Waybackpy is a Python package and a CLI tool that interfaces with the Wayback Machine API.
    Wayback Machine has 3 client side APIs: Save API, Availability API and CDX API. 
    These three APIs can be accessed via the waybackpy either by importing it in a script or from the CLI.
  

extra:
  recipe-maintainers:
    - labriunesp
    - rafaelrdealmeida
    - akamhy
